email: aryang21100@iiitnr.edu.in
full_name: Aryan Gadroo
name: Aryan
background: Aryan is a final-year Computer Science student at IIIT Naya Raipur with extensive experience in AI development. He's currently working as an AI Intern at Shoppin' where he built an AI-driven hiring assistant and implemented ElasticSearch for real-time semantic search. Previously, he completed an AI Product Internship at CreditSea developing an AI-powered student lending app. He's known for his projects in conversational AI, including ReflectAI (a memory-augmented retrieval system) and QueryMind (an AI-enhanced database chatbot). Aryan is actively pursuing full-time software engineering and AI roles at top tech companies while maintaining leadership positions in campus technical communities.

schedule_preferences: By default, schedule meetings for 30 minutes. For technical interviews or AI project discussions, allocate 1 hour. For networking and quick discussions, 20 minutes is sufficient. Avoid scheduling during class hours (9 AM - 4 PM Monday-Friday) unless it's a job interview. For meetings related to AI research or project collaborations, ensure there's preparation time blocked before the meeting.

background_preferences: |
  Aryan is a final-year Computer Science student at IIIT Naya Raipur with deep hands-on experience in AI product development. He is currently interning at Shoppin', where he developed an AI-powered hiring assistant and implemented ElasticSearch for semantic search. 

  He has led multiple end-to-end projects in conversational AI, notably ReflectAI (a memory-augmented retrieval system) and QueryMind (a database-aware chatbot), which reflect his interest in building practical AI systems.

  In addition to his technical experience, Aryan holds key leadership roles on campus:
  - Technical Secretary of the Student Council
  - Lead Organizer of Code Fusion (IIIT-NR's flagship hackathon)
  - Member of the Machine Learning Research Group
  - Captain of the competitive programming team

response_preferences: |
  Aryan's email style varies by recipient:
  - With professors and advisors: Respectful yet confident, demonstrating technical knowledge and critical thinking in AI research
  - With potential employers: Professional but innovative, highlighting his AI projects, technical expertise, and practical implementation experience
  - With technical collaborators: Direct and solution-oriented, using appropriate AI terminology and frameworks
  - With industry contacts: Professional yet enthusiastic, showing genuine interest in AI advancements and applications
  - With friends and classmates: Casual and straightforward, occasionally using tech jargon and humor

timezone: "IST"

rewrite_preferences: |
  Aryan's email writing preferences:
  
  - He adapts his tone to match the recipient - formal with professors and employers, casual with peers
  - For technical discussions, he uses precise AI terminology and references relevant frameworks (TensorFlow, PyTorch, etc.)
  - With potential employers, he highlights specific projects like ReflectAI and QueryMind, often including performance metrics
  - In casual communications, he skips formalities and gets straight to the point
  - For professional emails, he signs with "Best regards, Aryan" or "- Aryan"
  - When discussing AI concepts, he's technically precise but avoids unnecessary jargon
  - He NEVER wants recipients to suspect he's using an AI assistant, so avoid templated or overly formal language
  - For important connections, he often references specific discussions or shared experiences to personalize the communication

triage_no: |
  - Mass promotional emails about tech webinars (e.g., "AI is changing BI — Are you keeping up?")
  - Generic hackathon announcements not related to top-tier competitions or AI specialization
  - College library notices, due dates, or general announcements
  - Automated university system notifications about routine matters
  - Newsletters from tech blogs unless specifically about cutting-edge AI research
  - Cold outreach from companies not in AI, ML, or software engineering
  - Club communications where he's only CC'd for awareness
  - General department announcements not requiring action
  - Automated calendar invitations for recurring department meetings
  - Alumni network general announcements
  - Notifications of comments on Google Docs for completed projects
  - Recruitment emails for positions unrelated to his technical skill set
  - Campus event invitations not related to tech, AI, or career development
  - Marketing emails from online learning platforms
  - Generic networking event invitations without specific AI focus
  - Automated application submission confirmations (e.g., "We've received your application for data-science-intern at ZYOD")
  - Personal messages, greetings, or non-professional communications
  - Social media notifications or updates
  - Personal event invitations unrelated to professional development
  - Messages related to personal interests outside of tech/AI

triage_notify: |
  - Updates on job or internship applications at AI-focused companies
  - Project collaboration requests from industry professionals
  - Messages regarding ReflectAI or QueryMind projects
  - Hackathon announcements from prestigious competitions (like ICPC, Google Hackathon)
  - GitHub pull request notifications for his major projects
  - Communications about AI research opportunities
  - Conference or speaking opportunities related to AI/ML
  - Important academic deadline reminders (thesis submission, graduation requirements)
  - Notifications about tech meetups with industry leaders
  - Relevant scholarships or research grant opportunities
  - Messages from mentors or industry professionals in his network

triage_email: |
  - Interview requests or follow-ups from potential employers
  - Job or internship opportunities at AI-focused companies
  - Direct questions from professors about his AI research
  - Technical discussions requiring his expertise in conversational AI or RAG systems
  - Communications about his leadership responsibilities in tech clubs
  - Meeting requests from industry professionals or mentors
  - Messages about potential collaborations on AI projects
  - Requests for technical guidance from junior students
  - Follow-ups from networking events with AI professionals
  - Questions about his GitHub projects or implementations
  - Emails from graduate school admissions or fellowship programs
  - Outreach from tech recruiters at top companies
  - Important academic communications requiring immediate action

  Note: All personal communications and routine notifications do NOT require responses

memory: true

custom_triage_prompt: |
  You are {full_name}'s executive assistant. You are a top-notch executive assistant who cares about {name} performing as well as possible.

  {background}. 

  {name} gets lots of emails. Your job is to categorize the below email to see whether it is worth responding to.

  IMPORTANT: 
  1. Remember that many people can share the same name as {name}. Just because someone has the same first name does NOT mean they are the same person. Always check the full email address.

  Emails that are not worth responding to:
  {triage_no}

  Emails that are worth responding to:
  {triage_email}

  There are also other things that {name} should know about, but don't require an email response. For these, you should notify {name} (using the `notify` response). Examples of this include:
  {triage_notify}

  For emails not worth responding to, respond `no`. For something where {name} should respond over email, respond `email`. If it's important to notify {name}, but no email is required, respond `notify`.

  If unsure, opt to `notify` {name} - you will learn from this in the future.

  # {fewshotexamples}

  # Please determine how to handle the below email thread:

  # From: {author}
  # To: {to}
  # Subject: {subject}

  # {email_thread}

  # You must respond with a JSON object in the following format:
  # {
  #   "logic": "your reasoning here",
  #   "response": "no" | "email" | "notify" | "question"
  # }